/**
 * POST /api/checkout
 * Body: { readingId: string }
 *
 * Flow:
 *   1. Attempt free claim via claim_free_slot RPC (atomic).
 *      If successful → mark paid, skip Stripe, go to processing.
 *   2. Else if Stripe keys configured → create Checkout Session.
 *   3. Else (dev mode) → auto-mark paid, go to processing.
 */
import { NextRequest, NextResponse } from "next/server";
import { stripe, PRICE_MYR_CENTS } from "@/lib/stripe/client";
import { adminClient } from "@/lib/supabase/admin";
import { SITE_URL } from "@/lib/utils";

export async function POST(req: NextRequest) {
  const { readingId } = await req.json();
  if (!readingId) {
    return NextResponse.json({ error: "missing_id" }, { status: 400 });
  }

  const supabase = adminClient();
  const { data: reading } = await supabase
    .from("readings")
    .select("id, email, status")
    .eq("id", readingId)
    .single();
  if (!reading) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }

  const email = reading.email.toLowerCase().trim();

  // ── 1. Attempt free claim ─────────────────────────────────────
  const { data: claim } = await supabase.rpc("claim_free_slot", {
    p_email: email,
    p_reading_id: readingId,
  });
  if (claim?.ok) {
    await supabase
      .from("readings")
      .update({ status: "paid", amount_cents: 0 })
      .eq("id", readingId);
    return NextResponse.json({
      url: `${SITE_URL}/reading/${readingId}/processing?free=1`,
      free: true,
      remaining: claim.remaining,
    });
  }

  // ── 2. Paid flow via Stripe (if configured) ───────────────────
  const hasStripe =
    !!process.env.STRIPE_SECRET_KEY &&
    process.env.STRIPE_SECRET_KEY.startsWith("sk_") &&
    !process.env.STRIPE_SECRET_KEY.includes("placeholder");

  if (hasStripe) {
    const session = await stripe.checkout.sessions.create({
      mode: "payment",
      payment_method_types: ["card", "fpx", "grabpay"],
      customer_email: reading.email,
      line_items: [
        {
          price_data: {
            currency: "myr",
            unit_amount: PRICE_MYR_CENTS,
            product_data: {
              name: "AI Jyotish Reading",
              description:
                "Personalised Vedic astrology PDF generated by Claude AI + Swiss Ephemeris.",
            },
          },
          quantity: 1,
        },
      ],
      metadata: { reading_id: readingId },
      success_url: `${SITE_URL}/reading/${readingId}/processing?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${SITE_URL}/reading?cancelled=${readingId}`,
    });
    await supabase
      .from("readings")
      .update({ stripe_session_id: session.id })
      .eq("id", readingId);
    return NextResponse.json({ url: session.url });
  }

  // ── 3. Dev bypass (no Stripe keys yet) ────────────────────────
  await supabase.from("readings").update({ status: "paid" }).eq("id", readingId);
  return NextResponse.json({
    url: `${SITE_URL}/reading/${readingId}/processing?dev=1`,
    devBypass: true,
  });
}
