import PDFDocument from "pdfkit";
import path from "path";
import { SITE_NAME } from "@/lib/utils";

const FONT_DIR = path.join(process.cwd(), "src/lib/pdf/fonts");

interface PdfInput {
  markdown: string;
  clientName: string;
  language: string;
  birthDate: string;
  birthTime: string;
  birthPlace: string;
}

/** Render the AI-generated Markdown into a typeset PDF. Returns a Buffer. */
export async function renderReadingPdf(input: PdfInput): Promise<Buffer> {
  const isTamil = /tamil|தமிழ்/i.test(input.language);
  const bodyFont = isTamil
    ? path.join(FONT_DIR, "NotoSansTamil-Regular.ttf")
    : path.join(FONT_DIR, "NotoSerif-Regular.ttf");
  const boldFont = isTamil
    ? path.join(FONT_DIR, "NotoSansTamil-Bold.ttf")
    : path.join(FONT_DIR, "NotoSerif-Bold.ttf");

  const doc = new PDFDocument({
    size: "A4",
    margin: 60,
    info: {
      Title: `${input.clientName} — Jyotish Reading`,
      Author: SITE_NAME,
      Subject: "AI Vedic Astrology Reading",
    },
  });

  doc.registerFont("body", bodyFont);
  doc.registerFont("bold", boldFont);

  return await new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ───── Cover page ─────
    doc.fillColor("#4C1D95")
      .rect(0, 0, doc.page.width, doc.page.height).fill();

    doc.fillColor("#F97316").font("bold").fontSize(42)
      .text(SITE_NAME, 60, 120, { align: "center" });
    doc.fillColor("#FFFFFF").font("body").fontSize(14)
      .text("AI Vedic Astrology Reading", { align: "center" });

    doc.moveDown(6);
    doc.fillColor("#FDE68A").font("bold").fontSize(28)
      .text(input.clientName, { align: "center" });
    doc.fillColor("#FFFFFF").font("body").fontSize(12)
      .text(
        `${input.birthDate}  ·  ${input.birthTime}\n${input.birthPlace}`,
        { align: "center" },
      );

    doc.moveDown(6);
    doc.fillColor("#F5F3FF").fontSize(10)
      .text(
        `Generated by ${SITE_NAME} · Swiss Ephemeris (Lahiri) + Anthropic Claude AI\n` +
        `For guidance only. Review by certified astrologer.`,
        { align: "center" },
      );

    // ───── Body pages ─────
    doc.addPage({ size: "A4", margin: 60 });
    doc.fillColor("#1E1B4B");
    doc.font("body").fontSize(11);

    const lines = input.markdown.split("\n");
    for (const raw of lines) {
      const line = raw.trimEnd();
      if (line.startsWith("# ")) {
        if (doc.y > 100) doc.addPage();
        doc.moveDown(0.5);
        doc.font("bold").fontSize(22).fillColor("#7C2D12")
          .text(line.slice(2));
        doc.moveDown(0.3);
        doc.font("body").fontSize(11).fillColor("#1E1B4B");
      } else if (line.startsWith("## ")) {
        doc.moveDown(0.8);
        doc.font("bold").fontSize(15).fillColor("#EA580C")
          .text(line.slice(3));
        doc.moveDown(0.2);
        doc.font("body").fontSize(11).fillColor("#1E1B4B");
      } else if (line.startsWith("### ")) {
        doc.moveDown(0.4);
        doc.font("bold").fontSize(12).fillColor("#6D28D9")
          .text(line.slice(4));
        doc.font("body").fontSize(11).fillColor("#1E1B4B");
      } else if (line.startsWith("- ")) {
        doc.font("body").fontSize(11).fillColor("#1E1B4B")
          .text(`•  ${line.slice(2)}`, {
            indent: 20,
            paragraphGap: 3,
            align: "justify",
          });
      } else if (line.startsWith("**") && line.endsWith("**")) {
        doc.font("bold").text(line.replaceAll("**", ""));
        doc.font("body");
      } else if (line === "") {
        doc.moveDown(0.5);
      } else {
        doc.font("body").fontSize(11).fillColor("#1E1B4B")
          .text(cleanInline(line), { align: "justify", paragraphGap: 4 });
      }
    }

    // Footer on every page
    const pageRange = doc.bufferedPageRange();
    for (let i = 0; i < pageRange.count; i++) {
      doc.switchToPage(pageRange.start + i);
      doc.fontSize(8).fillColor("#6D28D9")
        .text(
          `${SITE_NAME} · robojyotish.com · page ${i + 1} of ${pageRange.count}`,
          60,
          doc.page.height - 40,
          { align: "center", width: doc.page.width - 120 },
        );
    }

    doc.end();
  });
}

function cleanInline(s: string): string {
  // Strip simple markdown emphasis markers for PDF readability.
  return s.replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1");
}
