import type { Metadata, Viewport } from "next";
import { Inter, Cormorant_Garamond, Noto_Sans_Tamil } from "next/font/google";
import { SITE_NAME, SITE_URL } from "@/lib/utils";
import { SupportButton } from "@/components/landing/SupportButton";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-cormorant",
});
const notoTamil = Noto_Sans_Tamil({
  subsets: ["tamil"],
  weight: ["400", "600", "700"],
  variable: "--font-tamil",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — AI Jyotish Reading | Vedic Astrology from RM19.90`,
    template: `%s | ${SITE_NAME}`,
  },
  description:
    "Get an accurate, AI-powered Hindu Jyotish (Vedic astrology) reading delivered as a downloadable PDF. Birth chart, dasha, nakshatra & life guidance — in English & Tamil. From RM19.90. Trusted by Malaysian, Singaporean & Indian clients.",
  keywords: [
    "AI jyotish reading",
    "Hindu jyotish online",
    "Vedic astrology Malaysia",
    "Tamil jyotish reading",
    "online birth chart Singapore",
    "AI astrology reading",
    "Robo jyotish",
    "cheap Vedic astrology reading",
    "jyotish PDF download",
    "nakshatra reading online",
    "dasha prediction AI",
    "Kundli online Malaysia",
    "astrology for Indians in Malaysia",
  ],
  authors: [{ name: SITE_NAME }],
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "AI Jyotish Reading — Vedic Astrology PDF from RM19.90",
    description:
      "Accurate AI-powered Vedic astrology reading. PDF delivered in English & Tamil. Malaysia, Singapore & India.",
    locale: "en_MY",
    alternateLocale: ["ta_IN", "ms_MY", "en_SG"],
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "RoboJyotish AI Vedic Astrology Reading",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Jyotish Reading from RM19.90 — RoboJyotish",
    description:
      "Vedic astrology PDF in English & Tamil, powered by AI. For Malaysia, Singapore & India.",
  },
  alternates: {
    canonical: SITE_URL,
    languages: {
      "en-MY": `${SITE_URL}/`,
      "ta-IN": `${SITE_URL}/ta`,
      "ms-MY": `${SITE_URL}/ms`,
      "x-default": `${SITE_URL}/`,
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  category: "lifestyle",
};

export const viewport: Viewport = {
  themeColor: "#4C1D95",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const orgLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_URL,
    logo: `${SITE_URL}/logo.png`,
    description:
      "AI-powered Hindu Vedic Jyotish readings delivered as PDF. English, Tamil & Bahasa Malaysia.",
    areaServed: ["MY", "SG", "IN"],
  };
  const productLd = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: "AI Jyotish Reading",
    description:
      "Personalized Vedic astrology reading generated by AI using accurate Swiss Ephemeris birth chart calculation. Delivered as PDF in your preferred language.",
    brand: { "@type": "Brand", name: SITE_NAME },
    offers: {
      "@type": "Offer",
      priceCurrency: "MYR",
      price: "19.90",
      availability: "https://schema.org/InStock",
      url: `${SITE_URL}/reading`,
    },
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.8",
      reviewCount: "127",
    },
  };
  const faqLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is AI Jyotish Reading?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "AI Jyotish Reading uses Swiss Ephemeris for accurate Vedic chart calculation, then generates personalized life interpretation using Claude AI across dasha, nakshatra, planetary positions, and life events you share.",
        },
      },
      {
        "@type": "Question",
        name: "How much does a reading cost?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "RM19.90 per reading — one of the most affordable Vedic astrology readings anywhere in the world.",
        },
      },
      {
        "@type": "Question",
        name: "Is the reading available in Tamil?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. Choose English, Tamil, Bahasa Malaysia, or any other language during checkout. The AI will generate your reading in every language you select.",
        },
      },
    ],
  };

  return (
    <html
      lang="en"
      className={`${inter.variable} ${cormorant.variable} ${notoTamil.variable}`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(productLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }}
        />
      </head>
      <body className="font-sans antialiased bg-cosmic-950 text-white min-h-screen">
        {children}
        <SupportButton />
      </body>
    </html>
  );
}
